### PR TITLE
PEP 8 compliance, Fixed error when no channel is specified

### PR DESCRIPTION
**Pull request by simon987**

### CODE REVIEW

**Comment by southbridge-fur** [comment]
Sorry I didn't see this pull request at the time. Feel free to reopen it and I'll review your changes.

**Comment by simon987** [comment]
No worries, I closed it because I ended up almost entirely rewriting the script.
If you want still want to merge let me know

**Comment by southbridge-fur** [comment]
Sure. I never really intended to modify this project any further and you've added valuable functionality that should be promoted.

**Comment by southbridge-fur** [comment]
If you're alright with it, I'll submit the merge. I've reviewed your changes and they've added significant improvements to the project.

**Comment by simon987** [comment]
Go ahead :+1:

**Comment by southbridge-fur** [comment]
Thanks for contributing!

**Pull request merged**
